### ISSUE TITLE
JTalk 記号の読み (^)

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajpmiscdep#52]
NVDA 2017.4JP-beta-171107wから、JTalkでの記号"^"の読み上げ方が変わっているようです。

1) キーボードから"^"を入力すると、「べき乗」と読み上げされます。
2) 1)の後、左矢印キーを押してカーソルを"^"の左に移動させると、「サーカムフレックスアクセント」と読み上げされます。

ちなみに、eSpeakでは、記号"^"は「キャレット」と読み上げされます。

「サーカムフレックスアクセント」という呼称は馴染みがなく、何の記号かわからず混乱するので、
（カーソルを戻したときに「サーカムフレックスアクセント」と読み上げされると、打ち間違えたか間違って変な記号を入力したのかと思ってしまう）
できれば、JTalkでの記号"^"の読みは「べき乗」に統一してほしいです。

**Comment by nishimotz** [comment]
下記の作業の影響のようなので、再調整させてください。

https://github.com/nvdajp/nvdajp/issues/58

**Comment by nishimotz** [comment]
「べき乗」に読み方を統一しました。
ご報告ありがとうございました。
