### ISSUE TITLE
JTalk 英単語の読み (NVDASR) 

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajpmiscdep#53]
nvdasr = エヌブイディーエイザ
と読みます。この手の場合はスペルアウトで良いかと思います。

**Comment by msuzu15** [comment]
既存単語の大文字表記+"SR"の場合に、
"SR"が"ズア"と読み上げされるようですね。

例：

WINDOWSSR
WORDSR
EXCELSR
JAWSSR
NVDASR

**Comment by mitsugusakamoto** [comment]
いえ、大文字で無くても読みます。上げていただいた例だと、
excelsr
jawssr
windowssr
などなどです。

**Comment by msuzu15** [comment]
この場合は「エスアール」ですね。

ExcelSR
JawsSR
WindowsSR

**Comment by msuzu15** [comment]
"SR"=「ズア」 → "SR"=「エスアール」という修正でよいのではないでしょうか。

**Comment by nishimotz** [comment]
NVDAは音声エンジンに送る前に（たぶん）以下のような前処理をします。

* 小文字の直後に大文字が来たら、スペースで区切る
* 区切られた文字列は、大文字をすべて小文字に変換して、音声エンジンに送る

結果として ExcelSR は excel sr として音声エンジンに渡されます。

nvdasr は JTalk がひとつの単語として解釈しますが、
形態素解析の英単語辞書、
形態素解析結果に対するローマ字カナ変換規則、
英単語の複数形や過去形を後処理する規則、
などが影響します。

ズアと読み上げるのは複数形処理の副作用かも知れません。

先に翻訳の締め切りがあるので、すこし時間をください。

**Comment by msuzu15** [comment]
既存単語小文字表記+"sr"、既存単語大文字表記+"SR"の対応は、あまり簡単な実装にならないように思われます。
（変更による他への影響が読めないという意味において）
指摘された単語だけ個別に対応するか、ユーザーが各自で辞書登録するなどして個別対応してもらうかといった対応になるかと思います。
（特にどう読むのが適切なのかユーザーによって分かれたり一つに特定できない場合）
また、単語の出現確立（そもそも日常の使用で出現することがあるのか）、深刻さ（運用で回避すればそれほど影響ないのか、日常の使用に著しい影響を与えるのか）などによっても対応が変わってくるかと思います。

ちなみに、他の音声エンジンでどのように読み上げされるか試してみました。

単語	eSpeak	JTalk	MSAPI5 (Kate)	MSAPI5 (Haruka)
nvdasr	エヌヴィーダーサ	エヌブイディーエーズア	エヌヴィーディーエーサ	ンダスル
windowssr	ウィンドウサ	ウインドウズズア	ウィンドウサ	ウインドウズ
NVDASR	エヌヴィーダーサ	エヌブイディーエーズア	エヌヴィーディーエーエスアール	ンダスル
WINDOWSSR	ウィンドウサ	ウインドウズズア	ダブリューアイエヌディーオーダブリューエスエスアール	ウインドウズ
NvdaSR	エヌヴィーディーエーエスアール	エヌヴイディーエーエスアール	エヌヴィーディーエーエスアール	ンダイスアール
WindowsSR	ウィンドウズエスアール	ウインドウズエスアール	ウィンドウズエスアール	ウィンドウズエスアール

**Comment by nishimotz** [comment]
まず nvdasr について調べています。
テキスト解析の結果に「S = ズ」「R = ア」の規則が適用されてしまっているようです。

```
input:    nvdasr
reading expected: 
reading result:   エヌブイディーエーズア
Mecab_print size: 3
0 ｎｖｄａ,名詞,一般,*,*,*,*,ｎｖｄａ,エヌブイディーエー,エヌブイディーエー,1/8,C0
1 ｓ,記号,アルファベット,*,*,*,*,ｓ,エス,エス,1/2,*
2 ｒ,記号,アルファベット,*,*,*,*,ｒ,アール,アール,1/3,*

Mecab_print size: 3
0 ,,,*,*,*,*
1 ,,,*,*,*,*
2 ｎｖｄａｓｒ,名詞,一般,*,*,*,*,ｎｖｄａｓｒ,エヌブイディーエーズア,エヌブイディーエーズア,0/10,C0


```

**Comment by nishimotz** [comment]
作業メモ

* SR を Mecab 辞書エントリにして「エスアール」と読むようにする
* 多くの事例はカバーできるが wordsr の解析で「 words + r 」が優先されてしまうので words という単語を辞書から抜く
* word を「ワード」 words を「ワーズ」と読むように辞書および規則を調整

**Comment by msuzu15** [comment]
NVDA 2017.4jp-beta-171115qで修正を確認しました。
