### ISSUE TITLE
[JTalk/点訳]京急線

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajpmiscdep#57]
JTalkの読みと点訳ですが、
京急線をきょうきゅうせん
と読み上げたり点訳したりするようです。

**Comment by msuzu15** [comment]
かなり以前から、「京急線」=「キョウキュウセン」、「京急」=「キョウキュウ」と読み上げられていますね。
（個人で辞書登録すればいい問題かと思っていままで特にレポートしませんでしたが）
ちなみに、
eSpeakでは「京急線」=「キョウキュウセン」、「京急」=「キョウキュウ」
Harukaでは、「京急線」=「ケイキュウセン」、「京急」=「ケイキュウ」
と読み上げられていますね。

**Comment by nishimotz** [comment]
現状の解析結果

```
Mecab_print size: 3
0 京,名詞,固有名詞,人名,姓,*,*,京,キョウ,キョー,1/2,C3
1 急,接頭詞,名詞接続,*,*,*,*,急,キュウ,キュー,0/2,P2
2 線,名詞,一般,*,*,*,*,線,セン,セン,1/2,C4
```

**Comment by nishimotz** [comment]
直っているはずなのでクローズします。

**Comment by mitsugusakamoto** [comment]
遅くなってすみませんが、直ってはいるんですが、「京急■線」のようにます空けされています。正しくはます開けをしません。

**Comment by nishimotz** [comment]
ます開けの処理の修正は、次のベータ版に反映される予定です。
