### ISSUE TITLE
JTalk 単語の読みの修正

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajpmiscdep#58]
以下、修正されるとありがたいです。
	（「単語」 - 「現状の読み」 - 「望ましい読み」の順）

「通帳」 - 「カヨイチョウ」 - 「ツウチョウ」
「someone」 - 「ソメオネ」 - 「サムワン」
「warehouse」 - 「ワレホウセ」 - 「ウェアハウス」

**Comment by msuzu15** [comment]
すみません、追加します。

「sometime」 - 「ソメチメ」 - 「サムタイム」
「teatime」 - 「テアチメ」 - 「ティータイム」

**Comment by msuzu15** [comment]
すみなせん、これも追加です。

「onsite」 - 「オンシテ」 - 「オンサイト」

**Comment by msuzu15** [comment]
すみません、これも検討お願い致します。

「注文書」 - 「チュウブンショ」 - 「チュウモンショ」

**Comment by nishimotz** [comment]
作業メモ
* 英単語同士の結合の場合は getKanaFromRoma() を使わないようにするべき
* 現状では mecab 辞書登録の品詞情報をうまく使えておらず、英単語登録の読みとそうでない読みを区別できていない
* たまたま bep-eng 辞書を0型アクセントで登録していることを利用して、0型アクセント同士の結合は英単語同士の結合と見なすようなワークアラウンドを実装している
* 将来もっときれいに実装するべき

**Comment by msuzu15** [comment]
今回の修正の影響かわかりませんが、ローマ字の読みが一部おかしくなっているところがあります。

例：
「Shigeo」 - 「シジェオ」 - 「シゲオ」
「Takeshi」 - 「テイクシ」 - 「タケシ」
「Mitsuo」 - 「ミットスオ」 - 「ミツオ」

このあたりトレードオフの問題かわかりませんが、
とりあえずご報告しておきます。

**Comment by nishimotz** [comment]
確認します。ご報告ありがとうございます。

**Comment by nishimotz** [comment]
作業メモ
* someone, warehouse, sometime の読みの修正をキャンセル
* 「0型アクセント同士の結合は英単語同士の結合と見なす」ワークアラウンドをやめる
* shigeo, takeshi, mitsuo の解析を元に戻す

**Comment by nishimotz** [comment]
他のケースをカバーできないが個別対応とする。
someone, warehouse, sometime を辞書に登録。
