### ISSUE TITLE
JTalk 英単語の読み （"ly"で終わる単語）

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajpmiscdep#59]
"ly"がつかないと英単語として読み上げるが、"ly"がつくとスペル読みになる英単語があります。
スペルは合っているので、英単語として読み上げされるとありがたいです。

例：
certain → certainly
obvious → obviously
recent → recently

"ly"がついても英単語として読み上げられるものもあります。

例：
complete → completely
general → generally
practical → practically

**Comment by nishimotz** [comment]
報告された3つのケースを確認したところ、
どれも「単語 + ly」のように解析されていなかったため、
この3つの単語を未知語として辞書登録する方針です。
泥臭い対応ですみませんが、他にも気になる単語が見つかったらお知らせください。
