### ISSUE TITLE
「銀四郎」、「立川談四楼」などの固有名詞の点字表記

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajpmiscdep#64]
### 期待されること (Expected behavior):
「ギンシロー」「タチカワ　ダンシロー」と仮名で点訳をする。

### 実際に起きること (Actual behavior):
「ギン4ロー」「タチカワ　ダン4ロー」と仮名で点訳をする。

### システム構成 (System configuration):
NVDA のバージョン (NVDA version):
NonVisual Desktop Access (NVDA)
Version: 2018.1jp-beta-171222m

インストール環境とポータブル版の種別 (NVDA Installed or portable):
Installed.

### 参考情報
点訳の手引き、第３版の第２章、「語の書き表し方」、「その2 数字」、「2 数を含む言葉の書き方」の以下の規則
4. 地名や人名などの固有名詞の中に使われている数字は、仮名で書くことを原則とする。

**Comment by nishimotz** [comment]
関連して nvdajp-team に以下の報告をいただきました。

```
安倍晋三・・・あべすすむ３　→　アベ　シンゾー
```

**Comment by nishimotz** [comment]
作業メモ
* 基本的に固有名詞を辞書登録するしか方法がない
* 今回は指摘していただいた人名だけを登録

**Comment by nishimotz** [comment]
メーリングリスト投稿 [nvdajp-team 7981] （点字表示の間違い例）をこのチケットでカバーします。

**Comment by nishimotz** [comment]
「凜々花」は点訳は直っているが JTalk の読み上げが「リンリンハナ」になっている。
踊り字の処理の影響かも知れない。
本件は点字表記に関するチケットなので、このまま close としておく。
