### ISSUE TITLE
NABCCで点字表示している時、数字に挟まれた"・"が半角ピリオドと同じ記号で表示される

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajpmiscdep#65]
### 問題の再現手順 (Steps to reproduce):

1. 点字表示をするように設定して コンピューター点字(NABCC)を使用をチェックする。
1. notepad 起動する。
1. 1・2・3　と入力する。

### 期待されること (Expected behavior):

数字に挟まれている中点は、５の点で表示される。

### 実際に起きること (Actual behavior):

数字に挟まれている中点が4,6の点で表示される。
4,6の点は、半角のピリオドと同じ記号である。数字に挟まれていても中点が表示されることが望ましい。

### システム構成 (System configuration):
NVDA のバージョン (NVDA version):

NVDAについて
NonVisual Desktop Access (NVDA)
Version: 2018.1jp-beta-180104l

インストール環境とポータブル版の種別 (NVDA Installed or portable):
Installed

**Comment by nishimotz** [comment]
現象は把握できました。
テキスト解析の副作用だということは分かったのですが、
もし期待通りに出力されたとして、
中点をあらわす「5の点」の後にマスアケが必要でしょうか？

**Comment by mitsugusakamoto** [comment]
中点の後ろはます開けで良いと思います。

**Comment by nishimotz** [comment]
ありがとうございます。修正します。
