### ISSUE TITLE
JTalk 文字列の読み（SC330100）

### ISSUE THREAD

**Issue by msuzu15** [nvdajp/nvdajpmiscdep#70]
「NVDA日本語版の問題の報告」を利用してください
https://github.com/nvdajp/nvdajp/issues
ただし問題の原因がJTalkまたは日本語点訳である場合にはこちらを利用可能です

### 問題の再現手順:
> 問題を再現する手順の箇条書き
>
> 例:
>
> 1. Chrome を開く
> 2. www.google.com を開く
> 3. "Hello" とキー入力する
> 4. Enter キーを押すとエラーの音が聞こえる

「SC330100」という文字列を読み上げさせると、「ッスシーサンサンゼロイチ」と読み上げされて、後ろの00が読み上げされません。
（メモ帳などに「SC330100」という文字列を入力してNVDA+↓キーで全文読み上げさせる、あるいは「SC330100」と書いてある行から下矢印キーを押してその行を読み上げさせることで現象を再現できます）

> 問題の再現に必要なファイルがあれば ZIP 形式のアーカイブで添付

### 期待されること:
> 何がどうなることを期待するか
「エスシーサンサンゼロイチゼロゼロ」と読み上げてほしいです。

### 実際に起きること:
> 実際には何が起きるか
「エスシーサンサンゼロイチ」と読み上げされます。

### システム構成
NVDA のバージョン
> 例: next-14027,c80e529f
NVDA 2018.2JP-Beta-180319s

インストール環境とポータブル版の種別
→　インストール版で確認しています。

その他の情報:
> 例: 仮想マシンで実行

Windows のバージョン:
> 例: Windows 10 バージョン 1607 ビルド 14393.1066
Windows 7 Enterprise SP1 64bit English

再現に必要なその他のアプリの名前やバージョン:

### その他の質問:

PC を再起動してもこの問題は再発しますか？
→　再発します。

その他のバージョンの NVDA で状況を比較しましたか？
> 比較した NVDA のバージョンと結果を箇条書きで

**Comment by nishimotz** [comment]
確認中です。
なぜか「3301」が単語として Open JTalk の辞書に入っていて、
その影響でおかしくなっているようです。
ちゃんと直す方法を調べていますが、まずは 3301 を辞書から抜いてみます。

**Comment by nishimotz** [comment]
2018.2jp-beta-180327p
SC330100 を「エスシー三十三万百」と読むようになりました。

**Comment by msuzu15** [comment]
確認しました。ありがとうございました。

ところで、前に日付6桁を読み上げさせるのに170221だけ他の日付（170220、170223など）と違う読み上げ方になっていたので気になっていたのですが、
どうやら"0221"でも今回と同じ現象が発生するようです。
（"18022100"を読み上げさせると後ろの00が読み上げされない）

**Comment by nishimotz** [comment]
2018.2jp-beta-180328l をリリースしました。
２文字以上の数字の単語を Open JTalk 辞書から機械的に削除しています。
ご確認ください。

**Comment by msuzu15** [comment]
NVDA 2018.2JP-Beta-180328lで確認しました。ありがとうございました。

**Comment by nishimotz** [comment]
読み上げるべき文字が欠落するのはよくない不具合なので、
2018.1.1jp に前倒しでマージします。
