### ISSUE TITLE
追従(ついじゅう)の点字表示

### ISSUE THREAD

**Issue by mitsugusakamoto** [nvdajp/nvdajpmiscdep#72]
### 問題の再現手順

1. notepad 起動。
2. 「追従」と入力する

### 期待されること

「ツイジュー」と点字表示する。

### 実際に起きること

「ツイショー」と点字表示される。
例: 
「フォーカス追従のカーソルの形」
「レビューカーソル追従のカーソルの形」

### システム構成
NonVisual Desktop Access (NVDA)
Version: 2018.2jp-beta-180420o

**Comment by nishimotz** [comment]
こちらでテストしたら JTalk の読み上げも点字出力も「ツイジュー」になります。

追従
⠝⠃⠘⠹⠒

**Comment by mitsugusakamoto** [comment]
何が違うのでしょう？アドオンとかのフォルダをすべて削除してまっさらな状態でもついしょうです。

**Comment by nishimotz** [comment]
私が基本的な勘違いをしているかも知れないので、
こちらでの「追従」の点訳結果は下記の通りです。
1345-12-45-1456-25

**Comment by mitsugusakamoto** [comment]
NVDA Version 2018.2jp-beta-180501nにしたら、直りました。これでいいと思います。
